apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: noc-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: noc-backend
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zabbix-backbone-password
  namespace: noc-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: zabbix-backbone-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: noc/zabbix-backbone-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zabbix-5gcore-password
  namespace: noc-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: zabbix-5gcore-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: noc/zabbix-5gcore-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: noc-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: noc/postgres-credentials
